export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const SET_PROVINCES = 'SET_PROVINCES'

export const GET_USERPROFILE = 'GET_USERPROFILE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE'
